-- Gesuche
select ZEBP_GESUCH.*, ZEBP_ENTSCHEID.*, TJ30T.*, ZEZS_CITY.*, ZEZS_DATES.*
from ZEBP_GESUCH
         left join ZEBP_ENTSCHEID on ZEBP_GESUCH.GESUCH_ID = ZEBP_ENTSCHEID.EXTERN_ID
         left join TJ30T on TJ30T.ESTAT = ZEBP_GESUCH.ESTAT and TJ30T.STSMA = 'ZEBP'
         left join ZEZS_CITY on ZEZS_CITY.CITY_ID = ZEBP_GESUCH.GEMEINDE_ID
         left join ZEZS_DATES on ZEBP_GESUCH.GESUCH_ID = ZEZS_DATES.EXTERN_ID and process_id = 'ZEBP' and TRMTYP = 'AFL'
where ZEBP_GESUCH.GESUCH_ID in ('EBPA-1720-6526', 'EBPA-8318-3681', 'EBPA-5618-4193', 'EBPA-4043-3357')
or ZEBP_GESUCH.GEMEINDE_BG in ('2025-500')

-- Standorte je Gesuch
select ZEBP_STORT.*, ZEZS_CITY.*, ZEBP_PARZ.*
from ZEBP_STORT
         left join ZEBP_PARZ on (ZEBP_STORT.city_id = ZEBP_PARZ.city_id and ZEBP_STORT.GESUCH_ID = ZEBP_PARZ.GESUCH_ID)
         left join ZEZS_CITY on ZEBP_STORT.CITY_ID = ZEZS_CITY.CITY_ID
where ZEBP_STORT.GESUCH_ID = 'EBPA-8318-3681'

-- Kontakte je Gesuch
select ZEBP_KONTAKT.*
from ZEBP_KONTAKT
where ZEBP_KONTAKT.GESUCH_ID = 'EBPA-5618-4193'

