select ZEBP_GESUCH.*, ZEBP_ENTSCHEID.*
from ZEBP_GESUCH
         left join ZEBP_ENTSCHEID on ZEBP_GESUCH.GESUCH_ID = ZEBP_ENTSCHEID.EXTERN_ID
where ZEBP_GESUCH.GESUCH_ID in ('EBPA-1720-6526', 'EBPA-8318-3681')

select * from ZEBP_GEMEIN where GESUCH_ID = 'EBPA-1720-6526'

select ZEBP_STORT.*, ZEZS_CITY.*, ZEBP_PARZ.*
from ZEBP_STORT
         left join ZEBP_PARZ on (ZEBP_STORT.city_id = ZEBP_PARZ.city_id and ZEBP_STORT.GESUCH_ID = ZEBP_PARZ.GESUCH_ID)
         left join ZEZS_CITY on ZEBP_STORT.CITY_ID = ZEZS_CITY.CITY_ID
where ZEBP_STORT.GESUCH_ID in ('EBPA-8318-3681')